### ISSUE TITLE
the classic: Index out of bounds exception

### ISSUE THREAD

**Issue by CameronLytle** [Mige5/rs2006sp#15]
(GraveMind)
I was banking a spade when the server got this error. It would load up the memory fast spitting out the same error over and over.
I've attached the hs_err_pid11884.log file that was generated when I tried to launch the server the second time.
I've copied over the server config file and the user config file and loaded everything up on the second instance. When I load up the game everthing works perfectly with all the same configurations.

I've also attached the cmd output of the server during the first crash.

I can't duplicate the issue in either the original intance nor the new one I spun up.
Because of the inconsistancy, feel free to close this ticket, I just figured I'd send you
the info I got and if any of it makes sense to you. I'll try to clip the event if it happens again.

[hs_err_pid11884.log](https://github.com/Mige5/rs2006sp/files/4495393/hs_err_pid11884.log)
![server log during crash Capture](https://user-images.githubusercontent.com/33914094/79616866-50280700-80c3-11ea-9ea5-0670f548c858.JPG)

**Comment by Mige5** [comment]
Next time post the error as text. (the part u have now posted as image)
