### ISSUE TITLE
Bots getting stuck 

### ISSUE THREAD

**Issue by DomeFossilx** [Mige5/rs2006sp#2]
Bots are getting stuck at the Crafting Guild for some reason.

*sent .dat file in discord*
![Screenshot at Oct 10 20-03-08](https://user-images.githubusercontent.com/54909553/66615061-43b57580-eb99-11e9-9968-9f4ff272fb4e.png)

an hour later:

![image](https://user-images.githubusercontent.com/54909553/66617471-40bf8280-eba3-11e9-9aba-3851949938e4.png)

**Comment by Mige5** [comment]
The bots should be fixed on next update.
