### ISSUE TITLE
Character and item models HDmod

### ISSUE THREAD

**Issue by Etherad** [Mige5/rs2006sp#23]
The model for Luthas from the Pirates Treasure quest's model when HDmod is active is missing the monkey and instead he is wearing a skill mastery cape.

The Chest inside the Blue Moon Inn within varrock used during the Pirates Treasure quest has had its model swapped out for two skill mastery capes, given it is still functioning and can be activated within the quest, one cape is for when it is closed, and briefly when it is opened its model quickly flicks to a different cape and then when it is closed again it returns to the first.

**Comment by Mige5** [comment]
Fixed on next update.

**Comment by Buogima** [comment]
Ive noticed the head chef within the cooking guuld comes to wear a skill cape too instead of a white apron and on the cooking guilds third floor the hopper turns into a hell hound! 
That one frightened me hah
