### ISSUE TITLE
Bot issue?

### ISSUE THREAD

**Issue by rspsgallus** [Mige5/rs2006sp#33]
Unsure what exactly is going on here lol. They are just walking back and forth between this shop and the bank and repeating "I'm going to train woodcutting."

**Comment by rspsgallus** [comment]
[woodcutting_bot_issue_unsure.zip](https://github.com/Mige5/rs2006sp/files/4727044/woodcutting_bot_issue_unsure.zip)

**Comment by Mige5** [comment]
Can u send me account file for a bot thats bugged.

**Comment by Mige5** [comment]
I think this issue has been fixed on next update.
