### ISSUE TITLE
Bots Mind runes RCing issue

### ISSUE THREAD

**Issue by NeedingName** [Mige5/rs2006sp#40]
I saw them make Air Runes without issues but they are stuck in the Mind Altar which I assume is because they don't see the exit portal from the Altar. Multiple bots are stuck after a single inventory.

**Comment by Mige5** [comment]
Send me a file of a bugged bot account.

**Comment by Mige5** [comment]
Fixed on next update.

**Comment by NeedingName** [comment]
Cheers man, keep up the amazing work!
