### ISSUE TITLE
Clear cut combat level perefences for pvp bots

### ISSUE THREAD

**Issue by AwesomeIbex** [Mige5/rs2006sp#5]
There seems to be a common cb level for some lower level bots (e.g 52).
It may be semantics but as a user i think it could be useful to A. customise the generated pvp bots so that we can improve our PVP experience. or B. Have a slightly broader bandwidth of outputs as i would argue 52 seems to be the favourite.

Happy to take a counter on that if i'm being silly though.

**Comment by Mige5** [comment]
Theres some restrictions to stats for all different types of bots like for example, 1 type could have it so they will always have 1 def, min 40 str, max 40 atk.. or something like that but yea the lvls are randomly generated and the combat lvl gets calculated from those.
